AWSTemplateFormatVersion: 2010-09-09

Description: >
  This Cloudformation Template creates a Jenkins Server on Docker machine on EC2 Instance. 
  Jenkins Server will run on Amazon Linux 2 (ami-026dea5602e368e96) EC2 Instance with
  custom security group allowing SSH (22) and HTTP (80, 8080) connections from anywhere.
Parameters:
  KeyPairName:
    Description: Enter the name of your Key Pair for SSH connections.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must one of the existing EC2 KeyPair

Resources:
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH to Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  Server:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dba2cb6798deb6d8
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !GetAtt ServerSecurityGroup.GroupId
      Tags:                
        -                        
          Key: Name
          Value: !Sub Server of ${AWS::StackName}   
      UserData:
        Fn::Base64: |
          #! /bin/bash
          apt-get update -y
Outputs:
  InstanceDNS:
    Description: Server DNS Name
    Value: !Sub 
      - ${PublicAddress}
      - PublicAddress: !GetAtt Server.PublicDnsName
